net-il-mio-fotoalbum/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using net_il_mio_fotoalbum.Database;
using net_il_mio_fotoalbum.Models;
using System.Data;

namespace net_il_mio_fotoalbum.Controllers
{
    public class CategoryController : Controller
    {
        [Authorize(Roles = "ADMIN")]
        public IActionResult Index()
        {
            ViewData["Title"] = "Homepage";
            using var ctx = new PhotoContext();

            var categoryList = ctx.Categories.ToArray();
            if (!ctx.Categories.Any())
            {
                ViewData["Message"] = "Nessuna categoria trovato";
            }
            return View("Index", categoryList);
        }

        [Authorize(Roles = "ADMIN")]
        [HttpGet]
        public IActionResult Create()
        {
            return View("Create");
        }

        [Authorize(Roles = "ADMIN")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category data)
        {
            using var ctx = new PhotoContext();
            if (!ModelState.IsValid)
            {
                return View("Create", data);
            }

            Category newCategory = new Category();
            newCategory.Name = data.Name;

            ctx.Categories.Add(newCategory);
            ctx.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "ADMIN")]
        [HttpGet]
        public IActionResult Edit(long id)
        {
            using var ctx = new PhotoContext();
            Category edit_category = ctx.Categories.Where(category => category.Id == id).FirstOrDefault();

            if (edit_category == null)
            {
                return NotFound();
            }
            else
            {
                return View(edit_category);
            }
        }

        [Authorize(Roles = "ADMIN")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(long id, Category data)
        {
            using var ctx = new PhotoContext();

            if (!ModelState.IsValid)
            {
                return View("Edit", data);
            }

            Category edit_category = ctx.Categories.Where(category => category.Id == id).FirstOrDefault();
            if (edit_category == null)
            {
                return NotFound();
            }
            edit_category.Name = data.Name;
            ctx.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "ADMIN")]
        public IActionResult Delete(long id)
        {
            using var ctx = new PhotoContext();
            Category category = ctx.Categories.Where(category => category.Id == id).FirstOrDefault();

            if (category == null)
            {
                return NotFound();
            }

            ctx.Categories.Remove(category);
            ctx.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

net-il-mio-fotoalbum/Controllers/PhotoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using net_il_mio_fotoalbum.Database;
using net_il_mio_fotoalbum.Models;

namespace net_il_mio_fotoalbum.Controllers
{
    public class PhotoController : Controller
    {
        [Authorize(Roles = "ADMIN")]
        public IActionResult Index()
        {
            ViewData["Title"] = "Homepage";
            using var ctx = new PhotoContext();

            var photoGallery = ctx.Photos.ToArray();
            if (!ctx.Photos.Any())
            {
                ViewData["Message"] = "Nessun risultato trovato";
            }
            return View("Index", photoGallery);
        }

        public IActionResult IndexUser()
        {
            return View();
        }

        public IActionResult Show(long id)
        {
            using var ctx = new PhotoContext();
            var singlePhoto = ctx.Photos.Include(photo => photo.Categories).First(photo => photo.Id == id);

            return View("Show", singlePhoto);
        }

        [Authorize(Roles = "ADMIN")]
        [HttpGet]
        public IActionResult Create()
        {
            using var ctx = new PhotoContext();

            PhotoFormModel model = new PhotoFormModel();
            model.Photo = new Photo();

            List<Category> categories = ctx.Categories.ToList();
            List<SelectListItem> listCategories = new List<SelectListItem>();
            foreach (Category category in categories)
            {
                listCategories.Add(new SelectListItem()
                {
                    Text = category.Name,
                    Value = category.Id.ToString()
                });
            }
            model.Categories = listCategories;

            return View("Create", model);
        }

        [Authorize(Roles = "ADMIN")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PhotoFormModel data)
        {
            using var ctx = new PhotoContext();
            if (!ModelState.IsValid)
            {

                List<Category> categories = ctx.Categories.ToList();
                List<SelectListItem> listCategories = new List<SelectListItem>();
                foreach (Category category in categories)
                {
                    listCategories.Add(new SelectListItem()
                    {
                        Text = category.Name,
                        Value = category.Id.ToString()
                    });
                }
                data.Categories = listCategories;
                return View("Create", data);
            }

            Photo newPhoto = new Photo();
            newPhoto.Title = data.Photo.Title;
            newPhoto.Description = data.Photo.Description;
            newPhoto.Url = data.Photo.Url;
            newPhoto.Visible = data.Photo.Visible;
            newPhoto.Categories = new List<Category>();

            if (data.SelectedCategories != null)
            {
                foreach (string selectedCategoryId in data.SelectedCategories)
                {
                    int selectedIntCategoryId = int.Parse(selectedCategoryId);
                    Category category = ctx.Categories.Where(x => x.Id == selectedIntCategoryId).FirstOrDefault();
                    newPhoto.Categories.Add(category);
                }
            }
            ctx.Photos.Add(newPhoto);
            ctx.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "ADMIN")]
        [HttpGet]
        public IActionResult Edit(long id)
        {
            using var ctx = new PhotoContext();

            Photo edit_photo = ctx.Photos.Where(photo => photo.Id == id).Include(photo => photo.Categories).FirstOrDefault();
            if (edit_photo == null)
            {
                return NotFound();
            }
            else
            {
                List<Category> categories = ctx.Categories.ToList();
                List<SelectListItem> listCategories = new List<SelectListItem>();
                foreach (Category category in categories)
                {
                    listCategories.Add(new SelectListItem()
                    {
                        Text = category.Name,
                        Value = category.Id.ToString()
                    });
                }

                PhotoFormModel model = new PhotoFormModel();
                model.Photo = edit_photo;
                model.Categories = listCategories;

                return View("Edit", model);
            }
        }

        [Authorize(Roles = "ADMIN")]
        [HttpPost]
        public IActionResult Update(long id, PhotoFormModel data)
        {
            using var ctx = new PhotoContext();

            if (!ModelState.IsValid)
            {

                List<Category> categories = ctx.Categories.ToList();
                List<SelectListItem> listCategories = new List<SelectListItem>();
                foreach (Category category in categories)
                {
                    listCategories.Add(new SelectListItem()
                    {
                        Text = category.Name,
                        Value = category.Id.ToString()
                    });
                }
                data.Photo = ctx.Photos.Where(p => p.Id == id).FirstOrDefault();
                data.Categories = listCategories;

                return View("Create", data);
            }

            Photo edit_photo = ctx.Photos.Where(photo => photo.Id == id).Include(photo => photo.Categories).FirstOrDefault();
            if (edit_photo == null)
            {
                return NotFound();
            }
            edit_photo.Title = data.Photo.Title;
            edit_photo.Description = data.Photo.Description;
            edit_photo.Url = data.Photo.Url;
            edit_photo.Visible = data.Photo.Visible;
            edit_photo.Categories.Clear();

            if (data.SelectedCategories != null)
            {
                foreach (string selectedCategoryId in data.SelectedCategories)
                {
                    int selectedIntCategoryId = int.Parse(selectedCategoryId);
                    Category category = ctx.Categories.Where(x => x.Id == selectedIntCategoryId).FirstOrDefault();
                    edit_photo.Categories.Add(category);
                }
            }
            ctx.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "ADMIN")]
        public IActionResult Delete(long id)
        {
            using var ctx = new PhotoContext();
            Photo photo = ctx.Photos.Where(photo => photo.Id == id).FirstOrDefault();

            if (photo == null)
            {
                return NotFound();
            }

            ctx.Photos.Remove(photo);
            ctx.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

net-il-mio-fotoalbum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - net_il_mio_fotoalbum</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/net_il_mio_fotoalbum.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">net_il_mio_fotoalbum</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Photo" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categorie</a>
                        </li>
                        <partial name="_loginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - net_il_mio_fotoalbum - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.5.1/axios.min.js" integrity="sha512-emSwuKiMyYedRwflbZB2ghzX8Cw8fmNVgZ6yQNNXXagFzFOaQmbvQ1vmDkddHjm5AITcBIZfC7k4ShQSjgPAmQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>